import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`font-primary antialiased p-6 background-gradient dark:text-neutral-C-0 text-neutral-C-900`}
      >
        {children}
      </body>
    </html>
  );
}
